export const APP_CONFIG_FILE = 'app.yml';

export const CONFIGURATION_SERVICE_TOKEN = Symbol('YML_CONFIG_SERVICE');

export const CONFIGURATION_TOKEN = 'YML_CONFIGURATION_TOKEN';
export const CONFIGURATION_LOADER = 'YML_CONFIGURATION_LOADER';
export const VALIDATED_ENV_LOADER = 'YML_VALIDATED_ENV_LOADER';

/* handle partial configuration keys */
export const PARTIAL_CONFIGURATION_KEY = 'YML_PARTIAL_CONFIGURATION_KEY';

export const PARTIAL_CONFIGURATION_PROPNAME = 'KEY';

export const VALIDATED_ENV_PROPNAME = '_YML_PROCESS_ENV_VALIDATED';

export const AS_PROVIDER_METHOD_KEY = 'asProvider';
